#ifndef UNTITLED2_ENUMS_H
#define UNTITLED2_ENUMS_H
enum Actions{
    PLAY,
    PAUSE,
    NEXT,
    PREVIOUS,
    ADD_STATION,
    MODIFY_STATION,
    DELETE_STATION,
    VIEW_ALL,
    HELP_TUNEIN,
    HELP_FILE
};

#endif //UNTITLED2_ENUMS_H
